### ISSUE TITLE
transition with Navigator.pushNamed()

### ISSUE THREAD

**Issue by tiaxter** [Salby/morph#3]
There's a method to build Morpheus transition and routing with routes already written and the Navigator.pushNamed?

**Comment by Salby** [comment]
If you want to use `MorpheusPageRoute` for named routes you'll have to write you routes a little differently. You'll also need version 0.8.0 or above.

Instead of this:
```dart
MaterialApp(
  routes: {
    '/': (context) => Home(),
    '/settings': (context) => Settings(),
  },
);
```

You'll have to write them like this:
```dart
MaterialApp(
  onGenerateRoute: (RouteSettings settings) {
    switch (settings.name) {
      case '/':
        return MorpheusPageRoute(
            builder: (context) => Home(),
            [...],
            settings: settings,
        );
      case '/settings':
        return MorpheusPageRoute(
            builder: (context) => Settings(),
            [...],
            settings: settings,
        );
    },
  },
);
```
[Link to stackoverflow question](https://stackoverflow.com/questions/51663793/how-to-use-cupertinopageroute-and-named-routes-in-flutter)

**Comment by tiaxter** [comment]
Thanks, it works <3
